name: masterelf
description: "Master Elf Feng Shui"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0  # For date formatting
  flutter_compass: ^0.8.1
  video_player: ^2.7.0
  lunar: ^1.7.4 # Add this package
  sensors_plus: ^6.1.1
  shared_preferences: ^2.2.2
  elegant_notification: ^2.4.5

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  permission_handler: ^12.0.0+1
  webview_flutter: ^4.4.2 # For web browser functionality
  lottie: ^3.3.1 # For Lottie animations
  flutter_blurhash: ^0.9.1 # For blur effect (optional, if needed)
  path_provider: ^2.1.1 # For saving files to the device
  share_plus: ^11.0.0   # For sharing the screenshot
  url_launcher: ^6.1.5
  connectivity_plus: ^6.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  font_awesome_flutter: ^10.1.0 # Add this line
  cupertino_calendar_picker: ^2.2.2
  dart_iztro: ^2.4.6
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/icons/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/lopanhd.png
     - assets/images/lopanhd2.png
     - assets/images/bg.jpg
     - assets/images/ybg.jpg
     - assets/images/row1a.png
     - assets/images/row1b.png
     - assets/images/row1c.png
     - assets/images/row2a.png
     - assets/images/row2b.png
     - assets/images/row2c.png
     - assets/images/row3a.png
     - assets/images/row3b.png
     - assets/images/row3c.png
     - assets/images/profile.png
     - assets/images/splash.jpg
     - assets/images/cover_image.jpg
     - assets/images/master_elf.jpg
     - assets/icons/telegram.png
     - assets/icons/tiktok.png
     - assets/videos/splash.mp4
     - assets/videos/pray.mp4
     - assets/icons/bazi.png
     - assets/icons/date.png
     - assets/icons/lopan.png
     - assets/icons/decor.png
     - assets/icons/more.png
     - assets/icons/pray.png
     - assets/icons/talisman.png
     - assets/icons/menu.png
     - assets/images/logo.png
     - assets/images/kaucim.png
     - assets/images/kaucim_stick.png
     - assets/images/intepretation.png
     - assets/images/yin.png
     - assets/images/yang.png
     - assets/images/standing.png
     - assets/images/moon_blocks.png
     - assets/images/profileicon.png
     - assets/images/star1.png
     - assets/images/star2.png
     - assets/images/star3.png
     - assets/images/star4.png
     - assets/images/star5.png
     - assets/images/star6.png
     - assets/images/star7.png
     - assets/images/star8.png
     - assets/images/star9.png
     - assets/jsons/loading_animation.json
     - assets/jsons/godofwealth.json
     - assets/jsons/purplestar.json
     - assets/jsons/redpocket.json
     - assets/jsons/thunder.json
     - assets/jsons/thunder2.json
     - assets/jsons/wave.json
     - assets/jsons/lightray.json
     - assets/audios/praying.mp3
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Dangrek
       fonts:
         - asset: assets/fonts/Dangrek-Regular.ttf
     - family: Siemreap
       fonts:
         - asset: assets/fonts/Siemreap-Regular.ttf
  #         weight: 700

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
